### ISSUE TITLE
Opening editor terminates far2l

### ISSUE THREAD

**Issue by cwollenhaupt** [elfmz/far2l#796] opened 2020-10-16 19:11 UTC
I built the current version using make, because the one line install failed for me. far2l works fine when I launch it. I can navigate and view files with F3. However, every time I open the editor, either by pressing F4 in the panel view or F6 from the file view window, then far2l simply disappears.

**Comment by strim** [comment] 2020-10-16 19:12
Same with my far2l build for Mac OS X Catalina 10.15.7

**Comment by cwollenhaupt** [comment] 2020-10-16 19:15
That's the same macOS version I'm using. I should have added that in the first place.

**Comment by strim** [comment] 2020-10-16 19:51
I checked the latest master, editor crashes as you described. Attaching [crash.log](https://github.com/elfmz/far2l/files/5393982/crash.log). As I can interpret, the culprit is colorer.

**Comment by singalen** [comment] 2020-10-16 20:43
I sent a pull request: #799.

**Comment by strim** [comment] 2020-10-16 21:23
Thanks a lot, I confirm the issue is fixed in my build with the latest master

**Closed** 2020-10-16 22:31 UTC
