### ISSUE TITLE
Bash aliases with "cd" are not working 

### ISSUE THREAD

**Issue by strim** [elfmz/far2l#487] opened 2019-01-16 19:44 UTC
I have a set of aliases in bash profile to quickly move between favorite directories. For example,

alias bin='cd ~/bin'
alias ws='cd ~/ws'

On `alias` command far2l shows the list of my aliases, i.e. its shell knows them. However, none of these aliases is able to change the directory. Likely, on alias execution far2l spawns new shell, runs `cd` command there, and then terminates the shell. The current directory of far2l panel is not changed as expected. Any advice? Can try to explore far2l sources to incorporate the changes if other people agree it is useful.

**Comment by rusq** [comment] 2019-03-05 09:01
You could use the standard Menu -> Commands -> **Folder shortcuts** functionality instead, which is more "native" to far:
<kbd>F9</kbd>+<kbd>c</kbd>+<kbd>d</kbd>

Then use <kbd>Right Ctrl</kbd>+<kbd>0</kbd>..<kbd>9</kbd> to quickly switch to your "bookmarked" folders.

**Comment by strim** [comment] 2019-03-06 20:15
Thank you for commenting. Sure, I can and I do use "Folder Shortcuts" :-) However, "Folder Shortcuts" override original native shortcuts to sort Far panel files by name, extension, modification date, etc. Moreover, it is simply not convenient to have special trick for Far only. I use Far in parallel with other terminals like iTerm2 for various activities. In normal terminals bash aliases work perfectly, so I love them and use automatically. Switching to Far window I need to remember that none of them works and Ctrl+0..9 sequence should be used instead.05.03.2019, 12:02, "Rustam" <notifications@github.com>:You could use the standard Menu -> Commands -> Folder shortcuts functionality instead, which is more "native" to far:
F9+c+d
Then use Right Ctrl+0..9 to quickly switch to your "bookmarked" folders.

**Comment by russiandesman** [comment] 2019-06-22 19:46
Hello colleagues, I faced the same issue and did some investigation in this regard.
The thing is that "cd" command must always be handled by far itself (the same is true for all shells, cd never implemented as a separate utility).
When processing command line Far knows nothing about aliases, so it just passes your alias to underlying shell, and it does change dir, but not for outer process (and this behavior is by design).
So the only way to teach Far process aliases with "cd" is to resolve aliases before command line processing, this way Far will see "cd" in resulting line and process it by itself.
The thing is to somehow obtain from BASH the value of BASH internal variable "${BASH_ALIASES[youraliashere]}". I tried to use popen to acquire it from bash but got nothing. After some investigation I realized that popen does not pass -i flag to bash and this leads to not-processing all these aliases from .bashrc. Right now I am working on manual ~/.bash_aliases parsing. This approach does not look correct to me though, so if anybody can advice how to get value of above mentioned bash variable -- I would be grateful.

**Comment by rusq** [comment] 2019-06-22 20:49
That’s a great idea @russiandesman , I would just like to add that not everyone uses bash, so this feature should have a flexibility to parse an arbitrary file I.e.  `.aliases` or `.profile`.  Or maybe even running the profile shell and capturing the output of `aliases` command

**Comment by russiandesman** [comment] 2019-06-24 09:19
So, here is my prototype. https://github.com/russiandesman/far2l/commit/293fa8ae55ac1cb9422dffdd21386b8a0d1c0a7d
It works, but it uses bash syntax and searches in dedicated file.
The best approach would be to run "alias" command in interactive shell and capture output. Right now I have no idea how to easily spawn interactive shell, I suppose Far2l already have such an API and I do not want to reinvent the wheel. As a quick and dirty solution this one is working.

**Comment by russiandesman** [comment] 2019-06-26 09:29
I am going to try interactive-popen version of this, hope it will not look so ugly as grep'ing aliases file...

**Comment by russiandesman** [comment] 2019-07-01 14:40
new prototype with resolving aliases with "alias" in interactive shell added. Currently works with bash only.
https://github.com/elfmz/far2l/compare/master...russiandesman:feature/aliases_resolving

**Comment by elfmz** [comment] 2019-07-01 19:23
why ipopen/ipclose? looks like they duplicate functionality of popen/pclose

**Comment by russiandesman** [comment] 2019-07-02 14:07
They are not :), popen gives non-interactive shell which does not process aliases, these ipopen\ipclose are dealing with interactive shell, thus allowing to resolve aliases (please note "-i" in execl arguments list).

Differences are easy to see in terminal, just try to issue ```bash -i -c alias``` and then ```bash -c alias```, latter one is what popen does.

**Comment by elfmz** [comment] 2019-07-02 14:14
but you same can pass -i to popen:  popen("bash -i -c alias", "r");

**Comment by russiandesman** [comment] 2019-07-02 18:46
something went wrong when I tried it last time, but let me check it again, if it works it would make the solution much cleaner.

**Comment by elfmz** [comment] 2019-07-02 19:09
there is however helper for popen: https://github.com/elfmz/far2l/blob/master/far2l/execute.cpp#L403

**Comment by russiandesman** [comment] 2019-07-03 17:30
Hello @elfmz,
thanks for advice, normal popen works too, now the solution is much simpler.
https://github.com/elfmz/far2l/compare/master...russiandesman:feature/aliases_resolving
@rusq, @strim please have a look.

**Comment by strim** [comment] 2019-07-23 23:25
Many thanks @russiandesman, I got the master version and bash aliases work fine! Sorry for not checking your change request timely, missed the notification.

**Comment by elfmz** [comment] 2019-07-24 06:54
note that there were some complains: https://github.com/elfmz/far2l/commit/209d625cfa4040f67b00e7e4eba1f5e7c05b002f#comments
and latest commit on master fixes them

**Comment by strim** [comment] 2019-07-25 04:25
Thank you @elfmz, I used latest source base and was very happy to see aliases working!

**Closed** 2019-07-28 10:06 UTC
