### ISSUE TITLE
shift-tab inserts strange garbage in command line

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1194] opened 2022-01-13 12:44 UTC
1) type some chars
2) press Shift-Tab

![изображение](https://user-images.githubusercontent.com/1151423/149332443-71776a59-b5b7-40cd-812f-c34ea895ea7f.png)

![изображение](https://user-images.githubusercontent.com/1151423/149332485-d08434ee-c598-4b32-98fe-edd82314910d.png)

**Comment by unwrecker** [comment] 2022-01-13 12:49
Автодополнение нормально срабатывает при единственном варианте дополнения. При множественных — выводит аналогичный список с битыми ecs-последовательностями. При множественном нажатии Tab на некоторое время подвисает без изменений на экране.

**Comment by ivanshatsky** [comment] 2022-01-13 13:35
The above screenshots are from
1. Typing "fa", Shift+Tab, Shift+Tab
2. Typing "re", Shift+Tab, Shift+Tab
However typing "di" and pressing Shift+Tab twice gives correct available commands list:
![image](https://user-images.githubusercontent.com/17809980/149339903-11e4dfa8-52e3-4b44-937a-d4627b43e3b9.png)

**Comment by ivanshatsky** [comment] 2022-01-14 23:32
Behavior changes, yet still isn't correct. However, now some behavior pattens can be tracked. Looks like the behavior depends on current path, logged user name and hostname. Here are some examples, tested under user `root` on a host with the name `free-tire-instance` (same host where above screenshots was taken, see `root@free-tier-instance` in the window title):

Current path is `/root/far/build`, typing "fa" ("fa" is the substring from the current path), Shift-Tab gives `far/buildfa` at the command prompt.

Current path is `/root/far/build`, typing "bui", Shift-Tab gives `buildbuil` at the command prompt.

Current path is `/`, typing either "fa" or "bui", Shift-Tab pressed twice gives correct menu of available commands started with "fa" or "bui".

Incorrect behavior also happens when typed string is the substring of `root@free-tier-instance`. Examples:

Typing "ro", Shift-Tab gives `root@free-tier-instance:/route`.

Typing "re", Shift-Tab gives `ree-tier-instance:/re`.

When typed string isn't a substring of either current path or `user@hostname` string, behavior seems to be correct.

**Comment by elfmz** [comment] 2022-01-18 00:12
Its not repro for me, however it potentially can depend on bash configuration. So i've added some logging (0cd4cede2b133101f4d80c6cf7a339958d5bf439), so please run current master then reproduce issue then collect file in /tmp/far2l_???/vtc.log and share that file (if it doesn't contain any private info) .
Better repeat that few times (with different commands) and share log from each attempt - cause that log is overwritten each time.

**Comment by elfmz** [comment] 2022-01-18 00:18
Also please share that logs as files (zip them and attach to message), but not copy-paste its content into message cuz it contains unprintable but yet important characters

**Comment by akruphi** [comment] 2022-01-18 14:57
> Its not repro for me, however it potentially can depend on bash configuration. So i've added some logging ([0cd4ced](https://github.com/elfmz/far2l/commit/0cd4cede2b133101f4d80c6cf7a339958d5bf439)), so please run current master then reproduce issue then collect file in /tmp/far2l_???/vtc.log and share that file (if it doesn't contain any private info) . Better repeat that few times (with different commands) and share log from each attempt - cause that log is overwritten each time. Also tell what OS you're trying on

In my Ubuntu 20.04 Far GUI for all attempts write in log:
```
bash: cannot set terminal process group (2882): Inappropriate ioctl for device
bash: no job control in this shell
```
and after 4-10 changes by keys UP/DOWN subwindows cropped in right panel (see screenshots)
![image](https://user-images.githubusercontent.com/92621645/149960035-cc50b7e6-886e-4f47-a6c4-5614ca8a1758.png)
![image](https://user-images.githubusercontent.com/92621645/149960344-7de518d5-8ac8-44f8-a13b-a90d3d96f0d0.png)
[vtc2.zip](https://github.com/elfmz/far2l/files/7889973/vtc2.zip)
[vtc1.zip](https://github.com/elfmz/far2l/files/7889974/vtc1.zip)

**Comment by ivanshatsky** [comment] 2022-01-18 17:41
Here are logs made for the [previously described](https://github.com/elfmz/far2l/issues/1194#issuecomment-1013541597) issues:
- `vtc.bui.log`: current path is `/root/far/build`, typing "bui", Shift+Tab.
- `vtc.fa.log`: current path is `/root/far/build`, typing "fa", Shift+Tab.
- `vtc.re.build.log`: current path is `/root/far/build`, typing "re", Shift+Tab.
- `vtc.re.root.log`: current path is `/`, typing "re", Shift+Tab.
- `vtc.ro.build.log`: current path is `/root/far/build`, typing "ro", Shift+Tab.
- `vtc.ro.root.log`: current path is `/`, typing "ro", Shift+Tab.

This is CentOS 7, `bash --verson` says `GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)`. Just in case everything related to bash configuration also included.
[logs.zip](https://github.com/elfmz/far2l/files/7891247/logs.zip)
[bash.config.zip](https://github.com/elfmz/far2l/files/7891252/bash.config.zip)

**Comment by elfmz** [comment] 2022-01-18 18:14
aha, see:
```
←]0;root@free-tier-instance:~/far/build•←[?1034h[root@free-tier-instance build]# PS1=''
←]0;root@free-tier-instance:~/far/build•bind -f "/tmp/far2l_0_0/vtc_inputrc"
←]0;root@free-tier-instance:~/far/build•true jkJHYvgT
←]0;root@free-tier-instance:~/far/build•bui•l
```
for some reason after `PS1=''` your bash still shows prompt, can you check on standalone bash? Type `PS1=''` and see if it will show command prompt after that

**Comment by ivanshatsky** [comment] 2022-01-18 18:38
Command prompt become an empty string (as it should) after `PS1=''`. Executing `far2l` after that, behavior is still the same, log files are identical. Putting `PS1=''` into the `/root/.bashrc`, logoff/logon, command prompt is empty, executing `far2l`, behavior does not changed.

**Comment by elfmz** [comment] 2022-01-18 19:38
Воспроизвел (и проблему и логи) на имеющейся под рукой Manjaro linux..

**Comment by elfmz** [comment] 2022-01-18 20:14
Check now plz..

**Comment by ivanshatsky** [comment] 2022-01-18 22:01
Commit `a626df6` fixes the problem. Many thanks!

**Comment by elfmz** [comment] 2022-01-18 22:31
closing then..

**Closed by elfmz** 2022-01-18 22:31 UTC

**Comment by unwrecker** [comment] 2022-01-19 09:20
![Screenshot from 2022-01-19 12-19-01](https://user-images.githubusercontent.com/870575/150100991-8024e270-00e1-4dfc-8d5c-8ee82ea2a973.png)
Не вижу никакой разницы

**Comment by elfmz** [comment] 2022-01-19 11:35
пришлите свои конфиги баша

**Comment by unwrecker** [comment] 2022-01-19 12:13
> пришлите свои конфиги баша

`$ cat ~/.bashrc 
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

alias sshp="/home/me/.ssh/sshp"
alias far='far2l --tty --ee --nodetect=xi'

PATH="/home/me/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/me/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/me/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/me/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/me/perl5"; export PERL_MM_OPT;
`

**Comment by elfmz** [comment] 2022-01-19 20:28
а сейчас? если все еще проблемы - пришлите еще и ~/.inputrc если он у вас есть
