### ISSUE TITLE
FarColorer stalls (again)

### ISSUE THREAD

**Issue by gabest11** [elfmz/far2l#1752] opened 2023-07-15 12:38 UTC
I found issue #996 but this time it seems to be a different problem.

https://github.com/elfmz/far2l/commit/7aa83aab0760925946acfc9b50699c5c7ec7c6c4#diff-e7bae64492e436677a45531ab1c6ff883086874995f1fe5164db5c12a9ca4392
colorer/src/pcolorer2/FarEditorSet.cpp:1353
bool FarEditorSet::checkFarTrueMod() {...}

I tracked it back to this change.

Windows 11, putty4far2l v0.76. The server is Ubuntu 20.04.6, without any GUI.

```
Thread 6 (Thread 0x7f9feaffd700 (LWP 1081751)):
#0  0x00007f9ff1a8dfcb in __GI___select (nfds=17, readfds=0x7f9feaffcbe0, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000055c14a069a7c in FSNotify::WatcherProc (this=0x55c14c0aeaf0) at /home/gabest/far2l/utils/src/FSNotify.cpp:134
#2  0x000055c14a069919 in FSNotify::sWatcherProc (p=0x55c14c0aeaf0) at /home/gabest/far2l/utils/src/FSNotify.cpp:109
#3  0x00007f9ff1ec1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007f9ff1a98133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f9feb7fe700 (LWP 1081750)):
#0  0x00007f9ff1a8dfcb in __GI___select (nfds=14, readfds=0x7f9feb7fdbe0, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000055c14a069a7c in FSNotify::WatcherProc (this=0x55c14c0ac160) at /home/gabest/far2l/utils/src/FSNotify.cpp:134
#2  0x000055c14a069919 in FSNotify::sWatcherProc (p=0x55c14c0ac160) at /home/gabest/far2l/utils/src/FSNotify.cpp:109
#3  0x00007f9ff1ec1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#4  0x00007f9ff1a98133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f9febfff700 (LWP 1081747)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7ffccf39b69c) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7ffccf39b6a0, cond=0x7ffccf39b670) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7ffccf39b670, mutex=0x7ffccf39b6a0) at pthread_cond_wait.c:647
#3  0x00007f9ff1da7e30 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x000055c14a019d37 in TTYBackend::WriterThread (this=0x7ffccf39b5c0) at /home/gabest/far2l/WinPort/src/Backend/TTY/TTYBackend.cpp:312
#5  0x000055c14a0183d6 in TTYBackend::sWriterThread (p=0x7ffccf39b5c0) at /home/gabest/far2l/WinPort/src/Backend/TTY/TTYBackend.h:46
#6  0x00007f9ff1ec1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007f9ff1a98133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f9ff0fab700 (LWP 1081746)):
#0  0x00007f9ff1a8dfcb in __GI___select (nfds=11, readfds=0x7f9ff0fa9bb0, writefds=0x0, exceptfds=0x7f9ff0fa9c30, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000055c14a01dd88 in os_call_v<int, -1, int, fd_set*, fd_set*, fd_set*, timeval*> (pfn=0x7f9ff1a8df60 <__GI___select>) at /home/gabest/far2l/utils/include/os_call.hpp:10
#2  0x000055c14a01cf73 in os_call_int<int, fd_set*, fd_set*, fd_set*, timeval*> (pfn=0x7f9ff1a8df60 <__GI___select>) at /home/gabest/far2l/utils/include/os_call.hpp:29
#3  0x000055c14a019779 in TTYBackend::ReaderLoop (this=0x7ffccf39b5c0) at /home/gabest/far2l/WinPort/src/Backend/TTY/TTYBackend.cpp:246
#4  0x000055c14a0191cd in TTYBackend::ReaderThread (this=0x7ffccf39b5c0) at /home/gabest/far2l/WinPort/src/Backend/TTY/TTYBackend.cpp:194
#5  0x000055c14a0183b3 in TTYBackend::sReaderThread (p=0x7ffccf39b5c0) at /home/gabest/far2l/WinPort/src/Backend/TTY/TTYBackend.h:45
#6  0x00007f9ff1ec1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007f9ff1a98133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f9ff17ac700 (LWP 1081745)):
#0  0x00007f9ff1a8dfcb in __GI___select (nfds=10, readfds=0x7f9ff17aaba0, writefds=0x0, exceptfds=0x7f9ff17aac20, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000055c14a0620ae in LocalSocketServer::WaitForClient (this=0x55c14c04efd0, fd_cancel=7) at /home/gabest/far2l/utils/src/LocalSocket.cpp:191
#2  0x000055c14a00f558 in SudoAskpassServer::Thread (this=0x7ffccf39b900) at /home/gabest/far2l/WinPort/src/sudo/sudo_askpass_ipc.cpp:106
#3  0x000055c14a00ee0c in SudoAskpassServer::sThread (p=0x7ffccf39b900) at /home/gabest/far2l/WinPort/src/sudo/sudo_askpass_ipc.h:38
#4  0x00007f9ff1ec1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007f9ff1a98133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f9ff1976880 (LWP 1081744)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55c14c166a18) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55c14c166a20, cond=0x55c14c1669f0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55c14c1669f0, mutex=0x55c14c166a20) at pthread_cond_wait.c:647
#3  0x00007f9ff1da7e30 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x000055c14a06050b in Event::Wait (this=0x55c14c1669f0) at /home/gabest/far2l/utils/src/Event.cpp:40
#5  0x000055c14a01b6f1 in TTYBackend::Far2lInterract (this=0x7ffccf39b5c0, stk_ser=..., wait=true) at /home/gabest/far2l/WinPort/src/Backend/TTY/TTYBackend.cpp:685
#6  0x000055c14a01b2bd in TTYBackend::OnConsoleGetColorPalette (this=0x7ffccf39b5c0) at /home/gabest/far2l/WinPort/src/Backend/TTY/TTYBackend.cpp:614
#7  0x000055c14a001101 in ConsoleOutput::GetColorPalette (this=0x55c14c04f0a0) at /home/gabest/far2l/WinPort/src/ConsoleOutput.cpp:657
#8  0x000055c149fe145f in WINPORT_GetConsoleColorPalette () at /home/gabest/far2l/WinPort/src/APIConsole.cpp:353
#9  0x00007f9ff0533997 in FarEditorSet::checkFarTrueMod (this=0x55c14c14f820) at /home/gabest/far2l/colorer/src/pcolorer2/FarEditorSet.cpp:1355
#10 0x00007f9ff05339ba in FarEditorSet::checkConsoleAnnotationAvailable (this=0x55c14c14f820) at /home/gabest/far2l/colorer/src/pcolorer2/FarEditorSet.cpp:1360
#11 0x00007f9ff0530966 in FarEditorSet::ReloadBase (this=0x55c14c14f820) at /home/gabest/far2l/colorer/src/pcolorer2/FarEditorSet.cpp:1033
#12 0x00007f9ff052bd0a in FarEditorSet::FarEditorSet (this=0x55c14c14f820) at /home/gabest/far2l/colorer/src/pcolorer2/FarEditorSet.cpp:88
#13 0x00007f9ff053ee13 in ProcessEditorEventW (Event=0, Param=0x0) at /home/gabest/far2l/colorer/src/pcolorer2/pcolorer.cpp:198
#14 0x000055c149f835ee in PluginW::ProcessEditorEvent (this=0x55c14c0d3e40, Event=0, Param=0x0) at /home/gabest/far2l/far2l/src/plug/PluginW.cpp:806
#15 0x000055c149f76428 in PluginManager::ProcessEditorEvent (this=0x7ffccf39b2e8, Event=0, Param=0x0) at /home/gabest/far2l/far2l/src/plug/plugins.cpp:827
#16 0x000055c149e35f28 in FileEditor::Init (this=0x55c14c0c7720, Name=0x55c14c0a469c L"LICENSE.txt", codepage=4294967295, Title=0x0, InitFlags=1048576, StartLine=-1, StartChar=-1, PluginData=0x0, OpenModeExstFile=0) at /home/gabest/far2l/far2l/src/fileedit.cpp:659
#17 0x000055c149e34dd1 in FileEditor::FileEditor (this=0x55c14c0c7720, Name=0x55c14c0a469c L"LICENSE.txt", codepage=4294967295, InitFlags=1048576, StartLine=-1, StartChar=-1, PluginData=0x0, OpenModeExstFile=0) at /home/gabest/far2l/far2l/src/fileedit.cpp:333
#18 0x000055c149e50b26 in FileList::ProcessKey (this=0x55c14c0add70, Key=65651) at /home/gabest/far2l/far2l/src/filelist.cpp:1601
#19 0x000055c149e67709 in FilePanels::ProcessKey (this=0x55c14c0a0f10, Key=65651) at /home/gabest/far2l/far2l/src/filepanels.cpp:772
#20 0x000055c149eb9ecf in Manager::ProcessKey (this=0x55c14c0a9ff0, Key=65651) at /home/gabest/far2l/far2l/src/manager.cpp:1048
#21 0x000055c149eb9303 in Manager::ProcessMainLoop (this=0x55c14c0a9ff0) at /home/gabest/far2l/far2l/src/manager.cpp:719
#22 0x000055c149eb911b in Manager::EnterMainLoop (this=0x55c14c0a9ff0) at /home/gabest/far2l/far2l/src/manager.cpp:678
#23 0x000055c149eb5c71 in MainProcess (strEditViewArg=..., strDestName1=..., strDestName2=..., StartLine=-1, StartChar=-1) at /home/gabest/far2l/far2l/src/main.cpp:343
#24 0x000055c149eb715a in FarAppMain (argc=1, argv=0x55c14c04efb0) at /home/gabest/far2l/far2l/src/main.cpp:669
#25 0x000055c14a01c94d in WinPortMainTTY (full_exe_path=0x55c14c04ed90 "/usr/local/bin/far2l", std_in=3, std_out=4, nodetect=0x55c14a08d938 "", far2l_tty=true, esc_expiration=0, notify_pipe=6, argc=1, argv=0x55c14c04efb0, AppMain=0x55c149eb60aa <FarAppMain(int, char**)>, result=0x7ffccf39b810) at /home/gabest/far2l/WinPort/src/Backend/TTY/TTYBackend.cpp:1020
#26 0x000055c14a0119ff in WinPortMain (full_exe_path=0x55c14c04ed90 "/usr/local/bin/far2l", argc=1, argv=0x55c14c04efb0, AppMain=0x55c149eb60aa <FarAppMain(int, char**)>) at /home/gabest/far2l/WinPort/src/Backend/WinPortMain.cpp:437
#27 0x000055c149eb7a52 in main (argc=1, argv=0x7ffccf39bae8) at /home/gabest/far2l/far2l/src/main.cpp:831
```
```
cmake -DUSEWX=no -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1")
-- git hash: 7aa83aab
-- Build Type: Debug Version: 2.4.1-7aa83aab-beta
-- Enabling registry support due to enabled LEGACY
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- generating headers and languages
-- Building with libuchardet
-- Found Uchardet: /usr/lib/x86_64-linux-gnu/libuchardet.so
-- Building without GUI/wxWidgets backend due to USEWX=no
-- Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
-- Building without TTY X11 extensions due to X11 not found
-- ALIGN plugin enabled
-- AUTOWRAP plugin enabled
-- CALC plugin enabled
-- COLORER plugin enabled
-- Build Colorer: 1.0.5
-- Found Spdlog: /usr/include
-- Found Xerces-C: /usr/lib/x86_64-linux-gnu/libxerces-c.so
-- Found fmt: /usr/include (found version "6.1.2")
-- Found Xerces-C: /usr/lib/x86_64-linux-gnu/libxerces-c.so
-- COMPARE plugin enabled
-- DRAWLINE plugin enabled
-- EDITCASE plugin enabled
-- EDITORCOMP plugin enabled
-- FILECASE plugin enabled
-- INCSRCH plugin enabled
-- INSIDE plugin enabled
-- MULTIARC plugin enabled
-- Found LibArchive: /usr/lib/x86_64-linux-gnu/libarchive.so (found version "3.4.0")
-- Found PCRE: /usr/lib/x86_64-linux-gnu/libpcre.so
-- NETROCKS plugin enabled
-- Checking for module 'openssl'
--   Found openssl, version 1.1.1f
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- OpenSSL found -> enjoy FTPS support in NetRocks
-- Found LibSSH: /usr/lib/x86_64-linux-gnu/libssh.so (Required is at least version "0.5.0")
-- libssh found -> enjoy SFTP support in NetRocks
-- libsmbclient found -> enjoy SMB support in NetRocks
-- Found LibNfs: /usr/lib/x86_64-linux-gnu/libnfs.so
-- libnfs found -> enjoy NFS support in NetRocks
-- Found LibNEON: /usr/lib/x86_64-linux-gnu/libneon.so
-- libneon found -> enjoy WebDav support in NetRocks
-- PYTHON plugin disabled, use -DPYTHON=yes if you need it
-- SIMPLEINDENT plugin enabled
-- TMPPANEL plugin enabled
HEAD detached at 7aa83aab
nothing to commit, working tree clean
-- Creating debian/copyright: /home/gabest/far2l/_build/copyright
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gabest/far2l/_build
```

This is from 7aa83aab0760925946acfc9b50699c5c7ec7c6c4, but the latest does the same.

**Comment by elfmz** [comment] 2023-07-15 19:19
From this stacks - you're using TTY version in terminal with far2l extension - what exactly terminal software is used?
Is bug reproducible?

**Comment by gabest11** [comment] 2023-07-15 19:42
putty4far2l.exe 0.76 from unxed, but I just tried the second google search hit, ivanshatsky's and that does not get stuck loading the editor.

**Comment by elfmz** [comment] 2023-07-16 18:51
@unxed it reminds me some recent (and fixed) issue with ignoring unsupported sequences, was it fixed eventually?

**Comment by unxed** [comment] 2023-07-17 09:41
> was it fixed eventually?

Should be.

Can you please provide exact steps to reproduce the problem?

**Comment by gabest11** [comment] 2023-07-17 10:29
F4 on any file. Plugin Configuration / FarColorer hangs, too. 

As I wrote, I used your version of putty4far2l on Win11 and running far2l on Ubuntu 20 (also tried on Debian 5.10). 

Meanwhile, I discovered that other putty4far2l and that one works. It's not a fork on github, so I don't really know which one is the most up-to-date version.

**Comment by unxed** [comment] 2023-07-17 10:33
not reproduces for me

![изображение](https://github.com/elfmz/far2l/assets/1151423/37d43eb9-f84d-43ab-aae4-59c7e603357d)

**Comment by unxed** [comment] 2023-07-17 10:35
ivanshatsky's version is the most recent as mentioned in my version's readme

**Comment by gabest11** [comment] 2023-07-17 10:36
I'm on Windows and built far2l with USEWX=no, so no GUI. Could this make a difference? Current have no desktop Linux, but I'll try one in a virtual machine quick.

**Comment by unxed** [comment] 2023-07-17 10:40
Also tested USEWX=no version. Maybe special bug that only reproduced in Win 11? Btw, uploaded 100% guaranteed fresh build from current master, please try: https://raw.githubusercontent.com/unxed/putty4far2l/master/windows/putty.exe

**Comment by gabest11** [comment] 2023-07-17 10:45
No problem with this build! The old 0.76 I am using says gcc 9.3-win32 20200320, this one gcc 10-win32 20220113, that's the only difference I can see in the About box.

**Comment by gabest11** [comment] 2023-07-17 10:48
Could it be that I'm that stupid that I never tried to download it again from github and only looked at the version number thinking it is the latest, but really it was 3 years old?

**Comment by elfmz** [comment] 2023-07-17 11:31
closing since everything ok with recent versions

**Closed by elfmz** 2023-07-17 11:31 UTC
