### ISSUE TITLE
Add an option to replace characters with non-standard width with a substitute character such as "▪"

### ISSUE THREAD

**Issue by sirburpalot** [elfmz/far2l#1333] opened 2022-07-11 06:58 UTC
This could serve as a workaround in order to prevent characters with non-standard width, such as emojis or Asian characters, from breaking the layout while in TTY mode.

**Comment by elfmz** [comment] 2022-08-27 23:31
Check please with branch tty-multiwidth-chars - if all issues are fixed or not (and no new appeared))

**Comment by unxed** [comment] 2022-08-28 14:50
> Check please with branch tty-multiwidth-chars

#1255 still reproducable

**Comment by elfmz** [comment] 2022-08-28 22:40
Well there 're two opposite scenarios for terminal:
1 far2l running and displaying its interface that gets garbaged by double-width (or diactrical) chars to resolve this have to treat all characters as having unity width. Its because logic of far (errorously) assumes that all characters have same width and expect this from terminal. Thats what was addressed in this branch (actually there was workaround for that but it was buggy, now shuld be better)
2 some other app running in terminal emulator. Other app knows that chars have different width and expect terminal to display them accordingly.
.. its impossible to make single workaround that will fit all. Need to correct main far's logic and bring terminal to normal rendering, but its not workaround (and not simple:()

**Comment by unxed** [comment] 2022-08-30 16:12
far2l's layout in tty mode looks ok now

![изображение](https://user-images.githubusercontent.com/1151423/187487507-08f9ae9f-bf2b-4f87-8603-233c5834fdf7.png)

**Comment by unxed** [comment] 2022-11-05 17:51
@elfmz probably should be closed now?

**Comment by elfmz** [comment] 2022-11-05 18:08
yep, root of issue is fixed

**Closed by elfmz** 2022-11-05 18:08 UTC
