### ISSUE TITLE
paste hotkeys does not work in command line tools running from Far

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#98] opened 2016-09-20 20:32 UTC
how to reproduce:
1. run 'read' command from Far (without quotes)
2. try to paste something

Tested Ctrl-V, Ctrl-Shift-V, Shift-Ins.

gvfs-mount tool also shows this behavour (then asking for password)

**Comment by elfmz** [comment] 2016-09-20 21:19
duplicate of https://github.com/elfmz/far2l/issues/97

**Closed by elfmz** 2016-09-20 21:19 UTC
