### ISSUE TITLE
Pressing any key cause error message `./src/unix/utilsx11.cpp(894): assert "Assert failure" failed in wxGetKeyStateGTK(): Unsupported key, only modifiers can be used`

### ISSUE THREAD

**Issue by NTMan** [elfmz/far2l#292] opened 2017-08-06 12:28 UTC
Pressing any key cause error message `./src/unix/utilsx11.cpp(894): assert "Assert failure" failed in wxGetKeyStateGTK(): Unsupported key, only modifiers can be used`

![screenshot from 2017-08-06 17-25-47](https://user-images.githubusercontent.com/200750/29003232-5265e460-7acc-11e7-8cd5-ad8d496eb0b1.png)

Distro: Fedora Rawhide x86_64

ASSERT INFO:
./src/unix/utilsx11.cpp(894): assert "Assert failure" failed in wxGetKeyStateGTK(): Unsupported key, only modifiers can be used

BACKTRACE:
[1] wxGetKeyState(wxKeyCode)
[2] wx2INPUT_RECORD::wx2INPUT_RECORD(wxKeyEvent&, int)
[3] WinPortPanel::OnKeyDown(wxKeyEvent&)
[4] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[5] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[6] wxEvtHandler::TryHereOnly(wxEvent&)
[7] wxEvtHandler::ProcessEventLocally(wxEvent&)
[8] wxEvtHandler::ProcessEvent(wxEvent&)
[9] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[10] g_closure_invoke
[11] g_signal_emit_valist
[12] g_signal_emit
[13] gtk_window_propagate_key_event
[14] g_closure_invoke
[15] g_signal_emit_valist
[16] g_signal_emit
[17] gtk_main_do_event
[18] g_main_context_dispatch
[19] g_main_loop_run
[20] gtk_main
[21] wxGUIEventLoop::DoRun()
[22] wxEventLoopBase::Run()
[23] wxAppConsoleBase::MainLoop()
[24] wxEntry(int&, wchar_t**)
[25] WinPortMain
[26] main
[27] __libc_start_main
[28] _start

**Comment by lieff** [comment] 2017-08-06 15:34
Hmm, looks like bug in latest wx code https://github.com/wxWidgets/wxWidgets/blob/master/src/unix/utilsx11.cpp

This initial code looks ok https://github.com/wxWidgets/wxWidgets/pull/320/files

**Comment by elfmz** [comment] 2021-08-03 19:27
likely fixed by dd37d80f8 reopen if still reproducible

**Closed by elfmz** 2021-08-03 19:27 UTC

**Comment by raywood1** [comment] 2021-11-05 17:46
I found [a PEBKAC solution](https://raywoodcockslatest.wordpress.com/2021/11/05/veracrypt-wxgetkeystategtk/) to a similar problem.
