### ISSUE TITLE
please make far2l remember its window position and size (and restore them on restart)

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#46] opened 2016-09-08 00:43 UTC

**Comment by invy** [comment] 2016-09-08 07:09
Duplicate of #16 ?

**Comment by unxed** [comment] 2016-09-18 20:31
#16 is not about window position, it's about window size only

**Comment by invy** [comment] 2016-09-19 09:44
Maybe this should be handled by wm?

**Comment by unxed** [comment] 2016-09-20 11:00
> Maybe this should be handled by wm?

Not sure about the right way to handle it, so please close this issue if you think this is not far's problem.

**Comment by unxed** [comment] 2016-10-19 04:19
from https://github.com/mate-desktop/marco

Q: Why does Marco remember the workspace/position of some apps
   but not others across logout/login?

A: Marco only stores sizes/positions for apps that are session
   managed. As far as I can determine, there is no way to attempt to
   remember workspace/position for non-session-aware apps without
   causing a lot of weird effects.

   The reason is that you don't know which non-SM-aware apps were
   launched by the session. When you initially log in, Marco sees a
   bunch of new windows appear. But it can't distinguish between
   windows that were stored in your session, or windows you just
   launched after logging in. If Marco tried to guess that a window
   was from the session, it could e.g. end up maximizing a dialog, or
   put a window you just launched on another desktop or in a weird
   place. And in fact I see a lot of bugs like this in window managers
   that try to handle non-session-aware apps.

   However, for session-aware apps, Marco can tell that the
   application instance is from the session and thus restore it
   reliably, assuming the app properly restores the windows it had
   open on session save.

   So the correct way to fix the situation is to make apps
   session-aware. libSM has come with X for years, it's very
   standardized, it's shared by GNOME and KDE - even twm is
   session-aware. So anyone who won't take a patch to add SM is more
   archaic than twm - and you should flame them. ;-)

   Docs on session management:
    http://www.fifi.org/doc/xspecs/xsmp.txt.gz
    http://www.fifi.org/doc/xspecs/SMlib.txt.gz

   See also the ICCCM section on SM. For MATE apps, use the
   MateClient object. For a simple example of using libSM directly,
   twm/session.c in the twm source code is pretty easy to understand.

**Comment by lingvoboard** [comment] 2017-01-02 12:29
Как временный вариант для растягивания окна во весь экран можно использовать следующий макрос:
Ctrl-<.> 
F9 c v (переключение "Video mode")
Ctrl-Shift-<.> (to a record in special mode)
Execute after FAR start - OK
Empty command line - OK
________________
Т.е. этот макрос сразу после старта меняет "Video mode"
Но лучше конечно будет если появится когда-нибудь команды --maximise  и --geometry=GEOMETRY (как у terminator-а к примеру)

**Comment by unxed** [comment] 2018-11-05 22:54
`/bin/bash -c "far2l & sleep .3 && wmctrl -r ":ACTIVE:" -b toggle,maximized_vert,maximized_horz"`

Я вот так делаю, например :)

**Comment by unxed** [comment] 2018-11-06 20:42
А вообще, конечно, галка в настройках "Start maximized" была бы очень кстати ;)

**Closed** 2023-01-05 11:18 UTC
